import streamlit as st
from google.cloud import firestore
import pandas as pd

# Setup the page
st.set_page_config(page_title="AI Fitness Dashboard", page_icon="💪", layout="centered")

st.title("💪 My AI Fitness Journey")
st.markdown("Your personalized daily HIIT routines generated by Gemini, pulled securely from Firestore.")

# Initialize Firestore client (uses local gcloud credentials)
@st.cache_resource
def get_db():
    return firestore.Client(project="fitnessapp-504108")

db = get_db()

# Fetch workouts
@st.cache_data(ttl=60)
def fetch_workouts():
    workouts_ref = db.collection("workouts").order_by("timestamp", direction=firestore.Query.DESCENDING).limit(30)
    docs = workouts_ref.stream()
    
    workouts = []
    for doc in docs:
        data = doc.to_dict()
        workouts.append({
            "Date": data.get("timestamp").strftime("%Y-%m-%d %H:%M") if data.get("timestamp") else "Unknown",
            "Routine": data.get("routine", ""),
            "Muscle Groups": ", ".join(data.get("muscle_groups", []))
        })
    return workouts

workouts = fetch_workouts()

if not workouts:
    st.info("No workouts found yet. The AI will generate one tomorrow morning!")
else:
    for w in workouts:
        with st.expander(f"🏋️ Workout from {w['Date']} - Focus: {w['Muscle Groups']}"):
            st.text(w['Routine'])
